import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  turbopack: {
    root: __dirname,
  },
  env: {
    NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT,
    NEXT_PUBLIC_APPWRITE_PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
    NEXT_PUBLIC_APPWRITE_DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID,
    NEXT_PUBLIC_APPWRITE_ACTIVITY_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_ACTIVITY_COLLECTION_ID,
    NEXT_PUBLIC_APPWRITE_CYCLES_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_CYCLES_COLLECTION_ID,
    NEXT_PUBLIC_APPWRITE_PARTICIPATION_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_PARTICIPATION_COLLECTION_ID,
  },
};

export default nextConfig;
