-- Veronica Gatekeeper System Migration
-- Adds GatekeeperReview and DailyReport tables

-- Gatekeeper reviews for user intake
CREATE TABLE IF NOT EXISTS gatekeeper_reviews (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "entityType"    TEXT NOT NULL, -- 'user_intake' | 'submission' | 'registration'
  "entityId"      TEXT NOT NULL,
  queue           TEXT NOT NULL DEFAULT 'new_users', -- 'new_users' | 'submissions' | 'returned'
  status          TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING' | 'VALID' | 'NEEDS_REVIEW' | 'FLAGGED' | 'APPROVED' | 'REJECTED' | 'SENT_BACK'
  "veronicaScore" REAL,
  "veronicaFlags" TEXT, -- JSON array of flag strings
  "veronicaNotes" TEXT,
  "reviewedBy"    TEXT,
  "reviewedAt"    TIMESTAMP,
  notes           TEXT,
  "createdAt"     TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt"     TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Daily reports generated by the system
CREATE TABLE IF NOT EXISTS daily_reports (
  id              TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "reportDate"    DATE NOT NULL UNIQUE,
  "newSignups"    INTEGER NOT NULL DEFAULT 0,
  "approvedUsers" INTEGER NOT NULL DEFAULT 0,
  "rejectedUsers" INTEGER NOT NULL DEFAULT 0,
  "totalSubmissions" INTEGER NOT NULL DEFAULT 0,
  "approvedSubmissions" INTEGER NOT NULL DEFAULT 0,
  "rejectedSubmissions" INTEGER NOT NULL DEFAULT 0,
  "pendingSubmissions" INTEGER NOT NULL DEFAULT 0,
  "activeContributors" INTEGER NOT NULL DEFAULT 0,
  "inactiveContributors" INTEGER NOT NULL DEFAULT 0,
  "openCycles"    INTEGER NOT NULL DEFAULT 0,
  "pendingReviews" INTEGER NOT NULL DEFAULT 0,
  "flaggedItems"  INTEGER NOT NULL DEFAULT 0,
  metadata        TEXT, -- JSON for extra stats
  "generatedAt"   TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_gatekeeper_reviews_entity ON gatekeeper_reviews("entityType", "entityId");
CREATE INDEX IF NOT EXISTS idx_gatekeeper_reviews_queue ON gatekeeper_reviews(queue, status);
CREATE INDEX IF NOT EXISTS idx_daily_reports_date ON daily_reports("reportDate");
